### ISSUE TITLE
Update jokes.json

### ISSUE THREAD

**Issue by arpitsomani8** [swapagarwal/JARVIS-on-Messenger#1023]
Added more jokes for the JARVIS

**Comment by salma2vec** [comment]
Hi @arpitsomani8 ! I would love to work on this, could you please assign it to me ?

**Comment by salma2vec** [comment]
My PR is labeled as Ineligible Repository...It can still contribute to any public GitHub repository & count towards my progress provided that  pull request is labeled with hacktoberfest-accepted.

**Comment by arpitsomani8** [comment]
> 
> 
> Hi @arpitsomani8 ! I would love to work on this, could you please assign it to me ?

@SalmaBliss only the author of this repositories can assign you to a issue .

**Comment by arpitsomani8** [comment]
> 
> 
> My PR is labeled as Ineligible Repository...It can still contribute to any public GitHub repository & count towards my progress provided that pull request is labeled with hacktoberfest-accepted.

@SalmaBliss Its not that your PR is rejected, its the repository which is not maintained the authentic work is rejected.

**Comment by balajigupta14** [comment]
Use pyjokes module
