### ISSUE TITLE
Can JARVIS post images or Gifs?

### ISSUE THREAD

**Issue by UshalNaidoo** [swapagarwal/JARVIS-on-Messenger#114]
An example is, in the coin toss feature, instead of displaying text it shows an image or a gif of a coin showing the result (heads/tails). This can be used in the dice roll as well.

**Comment by swapagarwal** [comment]
Yes, see the [attachment](https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/templates/attachment.py) template. Use the Image type.
Awesome use case; I'll be merging the PRs this weekend.
