### ISSUE TITLE
Add images in coin and dice module

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#128]
As pointed out in #114,
Instead of displaying text, we can show an image or a gif of a coin showing the result (heads/tails).
This can be used in the dice roll as well.
See the [attachment](https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/templates/attachment.py) template. Use the Image type.

**Comment by mahim97** [comment]
I was trying this out and could get this kind of output, 
{"text": "heads", "quick_replies": [{"payload": "{\"entities\": null, \"intent\": \"coin\"}", "attachment": {"attachment": {"type": "Image", "payload": {"url": "http://coins.silvercoinstoday.com/wp-content/uploads/2010/10/America-the-Beautiful-Silver-Coin-Obverse.jpg"}}}, "content_type": "text", "title": "Flip again!"}]}

Is this fine, I am finding it difficult to test it on messenger, need some help with figuring out ACCESS_KEY.

**Comment by swapagarwal** [comment]
@mahim97, this is being worked on in #141
