### ISSUE TITLE
Xkcd: Show random comic

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#129]
Right now, it shows the latest.

**Comment by kiendang** [comment]
I'm thinking of getting the total number of comics from the "num" in the latest comics then choose a random comics from 1:num but that means having to make 2 http requests.

**Comment by Rohitp** [comment]
I'm thinking that you don't need two requests. Since xkcd updates thrice a week and we know how many comics are out as of the current timestamp, we just need a base number and we can add 3 to it for every week that passes to get the "num" for the random 1:num range.
