### ISSUE TITLE
Add quick replies to joke, fact and quote modules

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#131]
Refer https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/coin.py to add a quick reply (show me another, one more, etc.) in:
- [x] joke
- [x] fact
- [x] quote

**Comment by CoderOwl** [comment]
Pull request created at:
https://github.com/swapagarwal/JARVIS-on-Messenger/pull/140 for adding quick replies ("One More!" and "Show me a quote") in joke module.

**Comment by srulih** [comment]
Hi I'm new to open source and i'd like to try this out. Is this project is still available and if so could you please provide some more details as to what I need to do.

**Comment by swapagarwal** [comment]
@srulih You can use the other commits as reference to update the `quote` module.

**Comment by chanondw** [comment]
pull request #211 for quick reply on quote
