### ISSUE TITLE
how to test ?

### ISSUE THREAD

**Issue by anilkunchalaece** [swapagarwal/JARVIS-on-Messenger#144]
Hi.. 
How to test this in the System ?
I Tried **Local Development / Testing** 
But it is showing output as 
![jarvis](https://cloud.githubusercontent.com/assets/17523245/21453086/db4c9e2e-c931-11e6-86f9-2f76c86db643.png)

**Comment by akanbrown** [comment]
`http://localhost:5000/search/?q=tell me a fact`

**Comment by swapagarwal** [comment]
@anilkunchalaece If you want to deploy a bot, follow the links given by @akanbrown.
If you want to test locally, visit the following URLs to see results:
`http://localhost:5000/process/?q=<<YOUR_QUERY>>` returns the intent of the query.
`http://localhost:5000/search/?q=<<YOUR_QUERY>>` returns the search result of the query.

e.g. "http://localhost:5000/process/?q=tell me a fact" returned the intent "fact".
Now you can visit "http://localhost:5000/search/?q=tell me a fact" to see the output.
