### ISSUE TITLE
Issue setting up environment

### ISSUE THREAD

**Issue by MatthewKarami** [swapagarwal/JARVIS-on-Messenger#145]
Hey guys! this is my first time delving into open source and I'm getting some issues while executing `pip install -r requirements.txt` (following the instructions on the README) My error message: 
![error](https://cloud.githubusercontent.com/assets/16831561/21473027/348fc8c4-caab-11e6-9f0e-41e012d26912.PNG)

I'm running windows 10 pro 64 bit and have python36-32 and the latest version of VS.

I've tried excecuting `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat`

I'd really appreciate any suggestions you guys have. Thanks!

**Comment by swapagarwal** [comment]
Any windows users here?
@MatthewKarami Are you using Python 2.7?

**Comment by MatthewKarami** [comment]
@swapagarwal No, I'm using 3.6. Should I be using 2.7?

**Comment by swapagarwal** [comment]
Yes 😅
