### ISSUE TITLE
Import error on Arch Linux

### ISSUE THREAD

**Issue by Icyphox** [swapagarwal/JARVIS-on-Messenger#146]
So I tried cloning this repo, and ran `python jarvis.py` and I get an `ImportError: No module named 'src'`.

Here's the complete traceback:
```
Traceback (most recent call last):
  File "jarvis.py", line 6, in <module>
    import modules
  File "/home/icyphox/Documents/coding/JARVIS-on-Messenger/modules/__init__.py", line 7, in <module>
    from src import *
ImportError: No module named 'src'
```

**Comment by BenjaminPollak** [comment]
Did you make sure to install the dependencies? There are some fairly straightforward directions for installing them at the bottom of  [this page](https://github.com/swapagarwal/JARVIS-on-Messenger), but it assumes the user is on a Debian-based distro. Have you taken a look at those?

**Comment by Icyphox** [comment]
Yes I have. And since Arch doesn't have any `-dev` packages, I'm sure I have the dependencies.

**Comment by swapagarwal** [comment]
@Icyphox Are you running on Python 2.7?
Can you attach a screenshot of your terminal?
Also, your help would be much appreciated in verifying #138 😄

**Comment by Icyphox** [comment]
@swapagarwal Nope. Running Python 3. Currently on my phone, will attach terminal screenshot after I get to my PC. 
As a temporary, yet annoying fix, I'm running Jarvis on an Ubuntu VM, and connecting to it through my host machine.

**Comment by swapagarwal** [comment]
@Icyphox Jarvis runs on Python 2.7 😇

**Comment by Icyphox** [comment]
Oh does it now? Silly me. :D
