### ISSUE TITLE
HTML entities in output

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#15]
Query: define a superhero
Response: ... in popular children`&#39;`s and fantasy literature ...
Expected: ... in popular children's and fantasy literature ...

**Comment by swapagarwal** [comment]
[this](http://fredericiana.com/2010/10/08/decoding-html-entities-to-text-in-python/) should do

**Comment by bopace** [comment]
I'd be happy to take a swing at this.

**Comment by swapagarwal** [comment]
@bopace Sure, go ahead!

**Comment by SaumyaRawat** [comment]
Hello! Are there any updates on this or can I take this up?

**Comment by bopace** [comment]
Go for it! I've been a little busier lately than I anticipated, so I won't be able to get to it for a bit.

**Comment by SaumyaRawat** [comment]
Great! Have been tinkering with the code a bit and found that `word = entities['dictionary'][0]['value']` is empty, for example, for "define comfort" it doesn't save "comfort" in word and it always gives an error message. Am I missing something obvious? Any clarifications will be appreciated! Thanks!

**Comment by swapagarwal** [comment]
@SaumyaRawat It is `word = entities['word'][0]['value']` See [Line#11](https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/dictionary.py#L11)

**Comment by SaumyaRawat** [comment]
Sorry! I forgot to change dictionary to word while I was posting. I had put that locally to test. But even `word = entities['word'][0]['value']` results in the same empty value for word

**Comment by swapagarwal** [comment]
Can you post the response you get from `http://localhost:5000/process/?q=define%20comfort`?

**Comment by SaumyaRawat** [comment]
> ["dictionary", {"word": [{"suggested": true, "confidence": 0.8058654087677778, "type": "value", "value": "comfort"}]}]

**Comment by SaumyaRawat** [comment]
It does have a value "comfort" according to this, will look at why the definition isn't displayed some more

**Comment by swapagarwal** [comment]
Output of `http://localhost:5000/search/?q=define%20comfort`?

**Comment by VarunWachaspati** [comment]
Kindly update the progress of the issue

**Comment by swapagarwal** [comment]
Hi @VarunWachaspati, this is yet to be done.

**Comment by shaishavgandhi05** [comment]
Was trying to replicate the issue but somehow the output for `http://localhost:5000/search/?q=define%20comfort` is 
`{"text": "I couldn't find that definition.\nPlease ask me something else, like:\n - define comfort\n - cloud definition\n - what does an accolade mean?"}`

Output for `http://localhost:5000/process/?q=define%20comfort` is 
`["dictionary", {"word": [{"suggested": true, "confidence": 0.8058654087677778, "type": "value", "value": "comfort"}]}]`

The API isn't working? Or am I missing something?

**Comment by shaishavgandhi05** [comment]
Never mind. Didn't realize had to enter my own API key

**Comment by AustinRow1** [comment]
I can't seem to replicate the original 'HTML Entity' bug when testing Jarvis locally. What can be done to replicate the bug locally?

**Comment by febinmoideen** [comment]
Is this still an issue?

**Comment by AustinRow1** [comment]
@febinmoideen , I'm unsure but I haven't been able to replicate this bug in my testing. The given usage case doesn't produce the bug nor do any tests that I have run myself. If you manage to reproduce it, let me know.

**Comment by swapagarwal** [comment]
This no longer seems to be an issue.
Also, the description in book module used to contain HTML tags, which has been fixed in fefc376ecdcf5938e6370ba6134350bc29b48b59
