### ISSUE TITLE
Lyrics: Search inside lyrics instead of title

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#156]
https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/lyrics.py#L12
Reference: https://developer.musixmatch.com/documentation/api-reference/track-search

**Comment by phil0s0pher** [comment]
Hey, this is my first time contributing to a project. I would like to try doing this.

**Comment by acquayefrank** [comment]
Hi, I wanted to work on this, but I started running into issues when I try to run the code.
Quick question - Does it work with python 3.  If not can I make it work  with both python 2 and 3

**Comment by swapagarwal** [comment]
Hi @phil0s0pher, thanks for taking an interest. It seems @acquayefrank has already created a PR for this. You may pick another one here: https://github.com/swapagarwal/JARVIS-on-Messenger/labels/Low-Hanging%20Fruit
@acquayefrank: It runs on Python 2.7

**Comment by aguy01** [comment]
i am novice. can i work on this project on desktop than mobile device? any mentor i can tag along with?

**Comment by narendravardi** [comment]
Hey @swapagarwal, does that mean using q_lyrics instead of q_track? Let me know if I am correct. Is there any one working on this? If not, can i work on this issue? I am a newbie too :)

**Comment by ringztech** [comment]
Hey, this is my first time contributing to a project. I would like to try doing this.

**Comment by KrMantavya** [comment]
Hey, I want to work on this!

**Comment by swapagarwal** [comment]
@KrMantavya Go ahead! 😄 
@aguy01 Yes, you can. Create an issue first describing what you'll be doing, and then you can post there if you run into any issues.
@narendravardi @ringztech You may pick another one from here: https://github.com/swapagarwal/JARVIS-on-Messenger/labels/Low-Hanging%20Fruit

**Comment by KrMantavya** [comment]
@swapagarwal Thankyou. Will try and raise a PR as soon as possible

**Comment by KrMantavya** [comment]
@swapagarwal please review my PR.
