### ISSUE TITLE
Changing Geocoding API and 'weather_location' in weather module

### ISSUE THREAD

**Issue by mayukh18** [swapagarwal/JARVIS-on-Messenger#165]
I suggest two things which I think will be better.

1. Shifting from mapquest api to google maps api for geocoding locations to longitude/latitude. The Google Maps API is more extensive and may help in case of extending other modules.

2. The 'weather_location' entity is limiting it's use case. Changing it to a more general 'location' entity is better else the wit.ai will be cluttered with many such location entities in the future having more or less the same utility.

I can actually submit the PR as I have already done it for my use. But there will remain the task of changing the wit.ai entity.

**Comment by swapagarwal** [comment]
Cool, I'll be waiting for the PR! 😄

**Comment by swapagarwal** [comment]
Hey @mayukh18, any update on this?

**Comment by mayukh18** [comment]
Sorry I forgot. l'll do it soon.

**Comment by swapagarwal** [comment]
Cool, np!
