### ISSUE TITLE
There was some error while retrieving data from NewsAPI.

### ISSUE THREAD

**Issue by pentagon98** [swapagarwal/JARVIS-on-Messenger#168]
I used Facebook Messenger.

The reply to news / latest new was:
"There was some error while retrieving data from NewsAPI."

I have attached the picture:
![jarvis_error](https://cloud.githubusercontent.com/assets/10035715/23042181/f5f40b54-f497-11e6-9f2f-3c43cae032df.jpg)

**Comment by chaseedward** [comment]
I believe this must have been a temporary error stemming from the API that is used (NewsAPI, https://newsapi.org/).  I have tried to replicate the error on separate occasions, on separate days and cannot get that error.
