### ISSUE TITLE
News module not working

### ISSUE THREAD

**Issue by vonnenaut** [swapagarwal/JARVIS-on-Messenger#171]
Query:  'latest news'
Response Message:  'There was some error while retrieving data from NewsAPI.'

I will look into this, though I will have to first get my bearings.

**Comment by vonnenaut** [comment]
Now it's working -- likely just a network issue.

**Comment by mayukh18** [comment]
check #168 
Probably, it's better to use another news source if this problem becomes way too frequent.

**Comment by yahyazini** [comment]
I'm having the same issue where I followed the guide:
* Add a new file in modules/src/ folder (define process function)
* Add some tests in modules/tests/ folder
* Add the module name in src/__init__.py

But the url keeps on returning [null, {}]

**Comment by swapagarwal** [comment]
@mayukh18 Makes sense. Right now, it seems stable!
@yahyazini Did you add the api key in config.py?
