### ISSUE TITLE
No module name 'src'

### ISSUE THREAD

**Issue by GroveIV** [swapagarwal/JARVIS-on-Messenger#175]
I have been attempting to set up Jarvis on messenger on my local machine, but I have run into a problem that I cannot seem to figure out.  First of all I am on a Windows machine and am using Python 3.4 (I searched and didn't see a reference to not using python 3).   When I attempt to run jarvis.py on the command prompt I get this error.

```
C:\Python34\python.exe C:/Python34/Jarvis/JARVIS-on-Messenger/jarvis.py
Traceback (most recent call last):
  File "C:/Python34/Jarvis/JARVIS-on-Messenger/jarvis.py", line 6, in <module>
    import modules
  File "C:\Python34\Jarvis\JARVIS-on-Messenger\modules\__init__.py", line 6, in <module>
    from src import *
ImportError: No module named 'src'

Process finished with exit code 1
```

It seems that the \_\_init\_\_.py isn't finding 'src'.  I thought about adding the package to the PYTHONPATH, but it doesn't seem like it should be necessary. 

Any feedback would be appreciated, I would love to contribute to this project.

**Comment by Bluer01** [comment]
I have the same issue. Followed the steps and got the same traceback.

**Comment by swapagarwal** [comment]
Jarvis runs on Python 2.
