### ISSUE TITLE
Duplicate facts

### ISSUE THREAD

**Issue by sks4903440** [swapagarwal/JARVIS-on-Messenger#177]
The bot displays the same fact after repeated queries.

![a](https://cloud.githubusercontent.com/assets/15520349/24078293/d53522b2-0c8f-11e7-9695-d0c0ed3b773b.png)

**Comment by edadesd** [comment]
It just looks like you drew the same random fact twice in three queries. There are currently only 11 facts in the data file, so I think this is to be expected a certain amount of time. It would happen less often overall if we added more facts to the bot.

**Comment by sks4903440** [comment]
Isn't there any API or a way to extract facts from [WTFFunFacts](http://wtffunfact.com/).

**Comment by swapagarwal** [comment]
@edadesd Correct!
@sks4903440 A quick search doesn't reveal any!

**Comment by katipallya** [comment]
@swapagarwal I'd like to take on the facts module - there must be a better way to do this than storing the facts locally.

**Comment by swapagarwal** [comment]
@katipallya Initially, joke/quote/fact modules used APIs. Now, they have switched to offline curated sources. You can find the reasoning in closed issues like #4
