### ISSUE TITLE
Cannot install on Windows - OpenSSL issue

### ISSUE THREAD

**Issue by Jamie22** [swapagarwal/JARVIS-on-Messenger#184]
When I try to do pip install on Windows I get the following error:

> build\temp.win32-3.6\Release\_openssl.c(713): error C2373: 'BIO_s_mem': redefinition; different type modifiers
>     C:\OpenSSL-Win32\include\openssl/bio.h(576): note: see declaration of 'BIO_s_mem'
>     build\temp.win32-3.6\Release\_openssl.c(714): error C2373: 'BIO_s_file': redefinition; different type modifiers
>     C:\OpenSSL-Win32\include\openssl/bio.h(532): note: see declaration of 'BIO_s_file'
>     build\temp.win32-3.6\Release\_openssl.c(717): error C2373: 'BIO_s_fd': redefinition; different type modifiers
>     C:\OpenSSL-Win32\include\openssl/bio.h(584): note: see declaration of 'BIO_s_fd'
>     build\temp.win32-3.6\Release\_openssl.c(719): error C2373: 'BIO_s_socket': redefinition; different type modifiers
>     C:\OpenSSL-Win32\include\openssl/bio.h(580): note: see declaration of 'BIO_s_socket'
>     build\temp.win32-3.6\Release\_openssl.c(721): error C2373: 'BIO_s_null': redefinition; different type modifiers
>     C:\OpenSSL-Win32\include\openssl/bio.h(587): note: see declaration of 'BIO_s_null'
>     build\temp.win32-3.6\Release\_openssl.c(735): error C2373: 'BIO_f_null': redefinition; different type modifiers
>     C:\OpenSSL-Win32\include\openssl/bio.h(588): note: see declaration of 'BIO_f_null'
>     build\temp.win32-3.6\Release\_openssl.c(736): error C2373: 'BIO_f_buffer': redefinition; different type modifiers
>     C:\OpenSSL-Win32\include\openssl/bio.h(589): note: see declaration of 'BIO_f_buffer'
>     build\temp.win32-3.6\Release\_openssl.c(743): warning C4030: first formal parameter list longer than the second list
>     build\temp.win32-3.6\Release\_openssl.c(747): warning C4002: too many actual parameters for macro 'CRYPTO_cleanup_all_ex_data'
>     build\temp.win32-3.6\Release\_openssl.c(747): error C2059: syntax error: 'while'
>     build\temp.win32-3.6\Release\_openssl.c(794): warning C4002: too many actual parameters for macro 'ENGINE_cleanup'
>     build\temp.win32-3.6\Release\_openssl.c(794): error C2059: syntax error: 'while'
>     build\temp.win32-3.6\Release\_openssl.c(871): warning C4002: too many actual parameters for macro 'ERR_free_strings'
>     build\temp.win32-3.6\Release\_openssl.c(871): error C2059: syntax error: 'while'
>     build\temp.win32-3.6\Release\_openssl.c(929): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(961): warning C4028: formal parameter 2 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(974): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1008): warning C4002: too many actual parameters for macro 'OBJ_cleanup'
>     build\temp.win32-3.6\Release\_openssl.c(1008): error C2059: syntax error: 'while'
>     build\temp.win32-3.6\Release\_openssl.c(1119): error C2371: 'ERR_load_RAND_strings': redefinition; different basic types
>     C:\OpenSSL-Win32\include\openssl/rand.h(76): note: see declaration of 'ERR_load_RAND_strings'
>     build\temp.win32-3.6\Release\_openssl.c(1126): warning C4002: too many actual parameters for macro 'RAND_cleanup'
>     build\temp.win32-3.6\Release\_openssl.c(1126): error C2059: syntax error: 'while'
>     build\temp.win32-3.6\Release\_openssl.c(1268): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1271): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1274): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1278): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1279): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1281): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1286): warning C4028: formal parameter 2 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1311): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1312): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1320): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1324): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1395): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1396): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1397): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1398): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1405): warning C4028: formal parameter 2 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1405): warning C4028: formal parameter 4 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1407): warning C4028: formal parameter 4 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1412): warning C4028: formal parameter 1 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1416): warning C4028: formal parameter 2 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1417): warning C4028: formal parameter 2 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1422): warning C4028: formal parameter 3 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(1422): warning C4028: formal parameter 4 different from declaration
>     build\temp.win32-3.6\Release\_openssl.c(2096): warning C4098: 'Cryptography_HMAC_CTX_free': 'void' function returning a value
>     build\temp.win32-3.6\Release\_openssl.c(6320): error C2065: 'SSL3_STATE': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6320): error C2059: syntax error: ')'
>     build\temp.win32-3.6\Release\_openssl.c(6410): error C2079: 'y' uses undefined struct 'evp_md_ctx_st'
>     build\temp.win32-3.6\Release\_openssl.c(6539): error C2037: left of 'version' specifies undefined struct/union 'ssl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6540): error C2037: left of 'type' specifies undefined struct/union 'ssl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6541): error C2065: 'SSL3_STATE': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6541): error C2065: 'tmp': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6541): error C2100: illegal indirection
>     build\temp.win32-3.6\Release\_openssl.c(6541): error C2037: left of 's3' specifies undefined struct/union 'ssl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6542): error C2037: left of 'session' specifies undefined struct/union 'ssl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6544): error C2079: 'y' uses undefined struct 'ssl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6547): error C2143: syntax error: missing ')' before '*'
>     build\temp.win32-3.6\Release\_openssl.c(6547): error C2143: syntax error: missing '{' before '*'
>     build\temp.win32-3.6\Release\_openssl.c(6547): error C2059: syntax error: ')'
>     build\temp.win32-3.6\Release\_openssl.c(6548): error C2054: expected '(' to follow 'p'
>     build\temp.win32-3.6\Release\_openssl.c(6554): error C2061: syntax error: identifier 'SSL3_STATE'
>     build\temp.win32-3.6\Release\_openssl.c(6554): error C2059: syntax error: '}'
>     build\temp.win32-3.6\Release\_openssl.c(6561): error C2037: left of 'master_key_length' specifies undefined struct/union 'ssl_session_st'
>     build\temp.win32-3.6\Release\_openssl.c(6562): error C2037: left of 'master_key' specifies undefined struct/union 'ssl_session_st'
>     build\temp.win32-3.6\Release\_openssl.c(6563): error C2037: left of 'session_id_length' specifies undefined struct/union 'ssl_session_st'
>     build\temp.win32-3.6\Release\_openssl.c(6564): error C2037: left of 'session_id' specifies undefined struct/union 'ssl_session_st'
>     build\temp.win32-3.6\Release\_openssl.c(6565): error C2037: left of 'sid_ctx_length' specifies undefined struct/union 'ssl_session_st'
>     build\temp.win32-3.6\Release\_openssl.c(6566): error C2037: left of 'sid_ctx' specifies undefined struct/union 'ssl_session_st'
>     build\temp.win32-3.6\Release\_openssl.c(6568): error C2079: 'y' uses undefined struct 'ssl_session_st'
>     build\temp.win32-3.6\Release\_openssl.c(6585): error C2037: left of 'sig_alg' specifies undefined struct/union 'x509_st'
>     build\temp.win32-3.6\Release\_openssl.c(6586): error C2037: left of 'cert_info' specifies undefined struct/union 'x509_st'
>     build\temp.win32-3.6\Release\_openssl.c(6587): error C2037: left of 'signature' specifies undefined struct/union 'x509_st'
>     build\temp.win32-3.6\Release\_openssl.c(6589): error C2079: 'y' uses undefined struct 'x509_st'
>     build\temp.win32-3.6\Release\_openssl.c(6625): error C2037: left of 'signature' specifies undefined struct/union 'x509_cinf_st'
>     build\temp.win32-3.6\Release\_openssl.c(6627): error C2079: 'y' uses undefined struct 'x509_cinf_st'
>     build\temp.win32-3.6\Release\_openssl.c(6634): error C2037: left of 'crl' specifies undefined struct/union 'X509_crl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6635): error C2037: left of 'sig_alg' specifies undefined struct/union 'X509_crl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6636): error C2037: left of 'signature' specifies undefined struct/union 'X509_crl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6638): error C2079: 'y' uses undefined struct 'X509_crl_st'
>     build\temp.win32-3.6\Release\_openssl.c(6645): error C2037: left of 'revoked' specifies undefined struct/union 'X509_crl_info_st'
>     build\temp.win32-3.6\Release\_openssl.c(6647): error C2079: 'y' uses undefined struct 'X509_crl_info_st'
>     build\temp.win32-3.6\Release\_openssl.c(6654): error C2037: left of 'object' specifies undefined struct/union 'X509_extension_st'
>     build\temp.win32-3.6\Release\_openssl.c(6655): error C2037: left of 'critical' specifies undefined struct/union 'X509_extension_st'
>     build\temp.win32-3.6\Release\_openssl.c(6656): error C2037: left of 'value' specifies undefined struct/union 'X509_extension_st'
>     build\temp.win32-3.6\Release\_openssl.c(6658): error C2079: 'y' uses undefined struct 'X509_extension_st'
>     build\temp.win32-3.6\Release\_openssl.c(6665): error C2037: left of 'req_info' specifies undefined struct/union 'X509_req_st'
>     build\temp.win32-3.6\Release\_openssl.c(6666): error C2037: left of 'sig_alg' specifies undefined struct/union 'X509_req_st'
>     build\temp.win32-3.6\Release\_openssl.c(6667): error C2037: left of 'signature' specifies undefined struct/union 'X509_req_st'
>     build\temp.win32-3.6\Release\_openssl.c(6669): error C2079: 'y' uses undefined struct 'X509_req_st'
>     build\temp.win32-3.6\Release\_openssl.c(6676): error C2037: left of 'serialNumber' specifies undefined struct/union 'x509_revoked_st'
>     build\temp.win32-3.6\Release\_openssl.c(6677): error C2037: left of 'revocationDate' specifies undefined struct/union 'x509_revoked_st'
>     build\temp.win32-3.6\Release\_openssl.c(6678): error C2037: left of 'extensions' specifies undefined struct/union 'x509_revoked_st'
>     build\temp.win32-3.6\Release\_openssl.c(6679): error C2037: left of 'sequence' specifies undefined struct/union 'x509_revoked_st'
>     build\temp.win32-3.6\Release\_openssl.c(6681): error C2079: 'y' uses undefined struct 'x509_revoked_st'
>     build\temp.win32-3.6\Release\_openssl.c(6706): error C2065: 'ASN1_F_ASN1_ENUMERATED_TO_BN': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6707): error C2065: 'ASN1_F_ASN1_ENUMERATED_TO_BN': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6727): error C2065: 'ASN1_F_ASN1_GENERALIZEDTIME_SET': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6728): error C2065: 'ASN1_F_ASN1_GENERALIZEDTIME_SET': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6811): error C2065: 'ASN1_F_ASN1_TIME_SET': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6812): error C2065: 'ASN1_F_ASN1_TIME_SET': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6832): error C2065: 'ASN1_F_ASN1_UNPACK_STRING': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6833): error C2065: 'ASN1_F_ASN1_UNPACK_STRING': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6839): error C2065: 'ASN1_F_ASN1_UTCTIME_SET': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6840): error C2065: 'ASN1_F_ASN1_UTCTIME_SET': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6874): error C2065: 'ASN1_F_BN_TO_ASN1_ENUMERATED': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6875): error C2065: 'ASN1_F_BN_TO_ASN1_ENUMERATED': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6881): error C2065: 'ASN1_F_BN_TO_ASN1_INTEGER': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6882): error C2065: 'ASN1_F_BN_TO_ASN1_INTEGER': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6888): error C2065: 'ASN1_F_D2I_ASN1_TYPE_BYTES': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6889): error C2065: 'ASN1_F_D2I_ASN1_TYPE_BYTES': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6902): error C2065: 'ASN1_F_D2I_ASN1_UTCTIME': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6903): error C2065: 'ASN1_F_D2I_ASN1_UTCTIME': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6909): error C2065: 'ASN1_F_D2I_NETSCAPE_RSA': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6910): error C2065: 'ASN1_F_D2I_NETSCAPE_RSA': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6916): error C2065: 'ASN1_F_D2I_NETSCAPE_RSA_2': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6917): error C2065: 'ASN1_F_D2I_NETSCAPE_RSA_2': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6930): error C2065: 'ASN1_F_D2I_X509': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6931): error C2065: 'ASN1_F_D2I_X509': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6937): error C2065: 'ASN1_F_D2I_X509_CINF': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6938): error C2065: 'ASN1_F_D2I_X509_CINF': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6944): error C2065: 'ASN1_F_D2I_X509_PKEY': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6945): error C2065: 'ASN1_F_D2I_X509_PKEY': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6951): error C2065: 'ASN1_F_I2D_ASN1_SET': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6952): error C2065: 'ASN1_F_I2D_ASN1_SET': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6958): error C2065: 'ASN1_F_I2D_ASN1_TIME': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(6959): error C2065: 'ASN1_F_I2D_ASN1_TIME': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(7014): error C2065: 'ASN1_F_X509_CINF_NEW': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(7015): error C2065: 'ASN1_F_X509_CINF_NEW': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(7056): error C2065: 'ASN1_R_DECODING_ERROR': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(7057): error C2065: 'ASN1_R_DECODING_ERROR': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(7168): error C2065: 'ASN1_R_UNSUPPORTED_ENCRYPTION_ALGORITHM': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(7169): error C2065: 'ASN1_R_UNSUPPORTED_ENCRYPTION_ALGORITHM': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(7196): error C2065: 'ASN1_R_WRONG_TYPE': undeclared identifier
>     build\temp.win32-3.6\Release\_openssl.c(7196): fatal error C1003: error count exceeds 100; stopping compilation
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
> 
>     ----------------------------------------
> Command "c:\users\jamie\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jamie\\AppData\\Local\\Temp\\pip-build-tfnpr9ih\\cryptography\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\jamie\AppData\Local\Temp\pip-uefcemo5-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jamie\AppData\Local\Temp\pip-build-tfnpr9ih\cryptography\

I tried both the 32 and 64 bit developer binaries from https://slproweb.com/products/Win32OpenSSL.html, and then followed the instructions by jsonm at http://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py

I'm new to Python and don't know much about OpenSSL. Does anyone know what I should do?

**Comment by Jamie22** [comment]
3.6

**Comment by swapagarwal** [comment]
Jarvis runs on Python 2. 😅
