### ISSUE TITLE
Wit's handling of currency conversion

### ISSUE THREAD

**Issue by ActualSize** [swapagarwal/JARVIS-on-Messenger#186]
Currently, wit does not recognise all currencies available from fixer.io. '10 AUD to USD' will not work but '10 USD to AUD' will.

As far as I can see the error comes directly after the api.wit.ai request, which results in data such as:

`["currency", {"to_currency": [{"confidence": 1, "type": "value", "value": "aud"}, {"suggested": true, "confidence": 0.93904722146817, "type": "value", "value": "ind"}]}]`

It ought to return the:

`["currency", {"to_currency": [{"suggested": true, "confidence": 0.94156114437978, "type": "value", "value": "ind"}], "from_currency": [{"confidence": 0.98750996453024, "type": "value", "value": "aud"}]}]`

**Comment by swapagarwal** [comment]
@ActualSize "10 AUD to USD" works now. It depends on how the bot is trained. 😅 
If we can make a list of what scenarios are not working, that'd be quite helpful as the bot can be trained with those queries then!

**Comment by ActualSize** [comment]
Yeah, I poked around in wit just after lodging this. I just didn't know how wit worked well enough, I understand how it works now.
