### ISSUE TITLE
Anime: Add more data

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#187]
Following data can be added to anime response:
- popularityRank
- ratingRank
- episodeCount
Feel free to suggest more!
Here's the API response: https://kitsu.io/api/edge/anime?filter[text]=naruto
The relevant fields should be added here: https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/anime.py#L20

**Comment by narendravardi** [comment]
@swapagarwal, can i work on this?

**Comment by narendravardi** [comment]
@swapagarwal, It would be good if we can add 'episodeLength' besides above mentioned details. Let me know your thought on this.
