### ISSUE TITLE
Anime: Add YouTube link

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#188]
Extract "youtubeVideoId" from the [API response](https://kitsu.io/api/edge/anime?filter[text]=naruto), and add another link [here](https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/anime.py#L24).

**Comment by ActualSize** [comment]
Could I do this one, I've never contributed before and this seems like a good starting point?

**Comment by guzmanga** [comment]
I would also like to try this one, if it's ok.

**Comment by sanjitjain2** [comment]
Hello, I'm interested, I am a first timer and would take some time to understand the code. Is this issue still open?
I would like to help.
Can someone guide me?

**Comment by shivam043** [comment]
Sorry sir,forgot to write the comment..
I have added a youtube link, Can you verify it??
