### ISSUE TITLE
Update the demo video

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#189]
The vimeo link is way too old!

**Comment by Redseb** [comment]
Hi, I know that you self-assigned the demo, but I was bored and decided to make one! Here's the Vimeo link: https://vimeo.com/226022581 

Tell me if I can PR :)

_Sent from my Xiaomi MI MAX 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by swapagarwal** [comment]
Hi Miko, that's an awesome demo! 😄 
I really liked the part towards the end. You should definitely send a PR. 🎉
