### ISSUE TITLE
Do you have a Designer?

### ISSUE THREAD

**Issue by jervlapsley** [swapagarwal/JARVIS-on-Messenger#195]
I'm an aspiring Graphic Designer, and student in programming and Information Technology. I want to give back to the industry by participating in Open Source Projects.

I will create a logo and any other graphic that you might need, and most likely help with the coding when I'm skilled enough.
Thanks.

**Comment by swapagarwal** [comment]
Hey Jervik, welcome to the amazing world of open-source! 🎉 
We don't have a designer yet, so you are more than welcome to contribute. A logo makes the first impression to users, and so I'd be extremely happy to have a logo designed for Jarvis.
I'd be looking forward to your contributions, both in design as well as in code. 😄

**Comment by swapagarwal** [comment]
@jervlapsley Let me know if you need any help!

**Comment by jervlapsley** [comment]
@swapagarwal Alright Thanks! I just started the logo sketches because I have been busy over the weeks

**Comment by swapagarwal** [comment]
Hey @jervlapsley, we have an ongoing issue pending, to add animations in coin and dice modules. Right now, it displays the outcome as an image. It'd be awesome to have a small animation to have an anticipation effect! See #152 
Would you be willing to pick that up?

**Comment by swapagarwal** [comment]
Closing in favor of #313
