### ISSUE TITLE
Python 3.5 - ImportError: No module named 'src'

### ISSUE THREAD

**Issue by AdamGreenhill** [swapagarwal/JARVIS-on-Messenger#2]
After installing the dependencies, and running the python code 

> $ python -V; printf "\n\n"; python jarvis.py 

I get the following error:

> Python 3.5.1
>
>
> Traceback (most recent call last):
>  File "jarvis.py", line 6, in <module>
>    import modules
>  File "/tmp/JARVIS-on-Messenger/modules/__init__.py", line 2, in <module>
>    from src import *
> ImportError: No module named 'src'
`

**Comment by swapagarwal** [comment]
As you can see in the README, we support only python 2.7 at the moment.
I'm closing this as we'll like to stick with one for now, with options being open to add / port to more versions / languages in the future if we get good contributions. :smile: 
If you face any problem while using this with the 2.7 version, feel free to reopen this at any time!
