### ISSUE TITLE
Ping: Add image in response

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#202]
Right now, `ping google.com` results in `google.com is up`.
We can add an image (green tick / red cross) to the response, for a better user experience.
Use `GenericTemplate` for this.

**Comment by leegenes** [comment]
I'd like to take a shot at this one, if that works. First time PR. I'll do a bit more digging, but seems pretty straight forward.

**Comment by swapagarwal** [comment]
Awesome, go ahead! 😄

**Comment by leegenes** [comment]
PR at #206
