### ISSUE TITLE
Optimize network calls

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#208]
Some of the API calls can be optimized by limiting the response.
e.g. If XYZ API returns 10 results by default, and we use only the top result; we can specify (in the request) how many items to return in the response, which optimizes the amount of data that gets transferred.
First Step: Figure out all such API calls.

**Comment by srulih** [comment]
Hi I'm new to open source. Could you please provide a bit more detail as to how I could complete this project?

**Comment by brandonmichaelhunter** [comment]
Good morning @swapagarwal  - so are say something adding an parameter to the API that allow the user to define the number of items to return?

**Comment by swapagarwal** [comment]
@srulih @brandonmichaelhunter User won't define the number of items to return. We shall limit it in our backend api calls as much as possible.
e.g. In `anime` module, the api call returns multiple results but we only use the top one. We can limit the response to return only one result by specifying a parameter in the call. Hope that makes sense! 😄

**Comment by Logan1x** [comment]
i would like to work on this
