### ISSUE TITLE
Images with square aspect ratio

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#209]
Previously, `GenericTemplate` only rendered images in the ratio 1.91:1. Now, we have the option of rendering it in 1:1 ratio! Check all modules where `GenericTemplate` is being used, and see jarvis' response to determine whether we should switch to square images in that module.
e.g. `ping` module uses square aspect ratio.

**Comment by pallavigopi** [comment]
Hey ! I am relatively new to open source! i would like to work on this bug. Would you provide me a few more inputs so that I can start working on it!

**Comment by pallavigopi** [comment]
Hi @swapagarwal ! 
The square template is used in music, news, ping, video, wiki and xkcd modules. We can switch the wiki module to square as it is more visually appealing. All the other modules are fine in the normal ratio.

**Comment by Logan1x** [comment]
hey @swapagarwal  can you explain me more on this.

**Comment by swapagarwal** [comment]
@pallavigopi Great!

**Comment by austinjcheng** [comment]
Submitted a PR that tweaked the modules that @pallavigopi mentioned.
