### ISSUE TITLE
Ping: Seems to only work with google.com

### ISSUE THREAD

**Issue by leegenes** [swapagarwal/JARVIS-on-Messenger#214]
Seems to be a problem with the ping module where only google.com returns a response from the module.

Receiving this error on all ping requests that aren't google.com:
I'm sorry; I'm not sure I understand what you're trying to say sir.
Try typing "help" or "request"

**Comment by leegenes** [comment]
Tangentially, might consider de-gendering the error message.

**Comment by swapagarwal** [comment]
@leegenes Can you share some sample queries?
Improving the error message makes sense.

**Comment by leegenes** [comment]
@swapagarwal 
ping amazon.com
ping isitup.org
ping yahoo.com

**Comment by swapagarwal** [comment]
@leegenes Trained wit using a couple more queries. Can you check now?

**Comment by leegenes** [comment]
@swapagarwal 
Working now. Though, site link and isitup.org link are now removed.

**Comment by swapagarwal** [comment]
Cool! Ohh, that was part of testing of an ongoing PR. 😜

**Comment by swapagarwal** [comment]
@leegenes The two links are now merged. 😄 
Tracking the other suggestion in #215
