### ISSUE TITLE
Gender-neutral responses

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#215]
Some messages are gender-specific, like:
```
I'm sorry; I'm not sure I understand what you're trying to say sir.
Try typing "help" or "request"
```
Can (Should) we make them gender-neutral?

**Comment by leegenes** [comment]
+1
Don't see added value in having a gendered answer, and do see potential for cases to detract from the bot's value for some users.

**Comment by edadesd** [comment]
+1
It's a good thing to strive for.

**Comment by ssummun54** [comment]
What about asking in the beginning for the sex and then he goes off of that. We could have a gender neutral option too

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by swapagarwal** [comment]
We can get the gender from the User Profile API. 🎉 
Just like we're getting the name [here](https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/__init__.py#L48), we can get more info about the [user](https://developers.facebook.com/docs/messenger-platform/user-profile).

**Comment by leegenes** [comment]
Safest bet seems to be using name, if that's available.

**Comment by pt2pham** [comment]
The gender is available in the API, names could include names that are applicable to both genders. 

_Sent from my Samsung SM-G930W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by leegenes** [comment]
@pt2pham - I guess I'm suggesting we skip gender. Just refer to people by name.

**Comment by pt2pham** [comment]
@leegenes ah I see, had a misunderstanding. That seems to be the best solution I'd agree.

_Sent from my Samsung SM-G930W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nicholassavini** [comment]
I agree with avoiding the concept of gender altogether. Some users may be equally turned off it were only presented as a binary option, and it seems to add little value to include gendered answers.

**Comment by sync350** [comment]
Is anyone actively working on this? Looks like the general consensus is to avoid using genders, and to refer to the user by name instead. I'd love to try my hand at this. It's my first time working with this kind of project, so I can't make any promises, but I'm willing to give it a shot.

**Comment by swapagarwal** [comment]
Based on the above discussions, the consensus is to avoid the concept of gender altogether.
