### ISSUE TITLE
Better dictionary API

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#22]
The current API is not so good; replace it with a better one!

**Comment by shanmukhateja** [comment]
Can you elaborate about what needs to be improved? I do not seem to follow

**Comment by swapagarwal** [comment]
See this file: https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/dictionary.py
In line number 8, we're using the Glosbe API, which doesn't return good results sometimes. We wish to replace this with a better API.

**Comment by shanmukhateja** [comment]
Is it okay if I make a web scrapper to deliver the results? I'm working on the Jokes list at the moment so I'll have to postpone this for a while.

**Comment by swapagarwal** [comment]
Scraping the web would be hacky! We'd like to use a proper API (for easy maintenance).
There's no rush; take your time. :smile:

**Comment by akarshHegde** [comment]
Hey, i would like to try this out with your help. This project seems interesting and a issue like this can help me get started

**Comment by shanmukhateja** [comment]
@swapagarwal  I've been looking into this API for a few days now and I feel their data is very apt.
For free service, they provide 2500 API calls per day.  (Not bad don't you think?)

Check their demo at [WordsAPI](https://www.wordsapi.com/).

**Comment by swapagarwal** [comment]
@shanmukhateja The WordsAPI looks good; I've signed up and set the environment variable `WORDS_API_KEY` on the server. However, as you're already a contributor, I feel like this time you can guide someone else with their first contribution. (what say?)
Hey @akarshHegde, the low-hanging fruits are solely for this purpose only! :smile:
The request is pretty simple: a GET request to `https://wordsapiv1.p.mashape.com/words/{word}/definitions` with `X-Mashape-Key` in its header.

**Comment by shanmukhateja** [comment]
I'll be happy to help. :)
@akarshHegde why don't you look at the present code that's used in JARVIS for an idea and later work your magic on it ;)

**Comment by akarshHegde** [comment]
@shanmukhateja @swapagarwal Thank you guys, Already looking into the code :)

**Comment by akarshHegde** [comment]
@swapagarwal ,  I am not able to figure out where is the access token. Any help?

**Comment by shanmukhateja** [comment]
I think there is no API in the present API but for the new one, you'll need to add an entry to config.py and later import it to dictionary module

**Comment by swapagarwal** [comment]
`os.environ.get('WORDS_API_KEY')`

**Comment by shanmukhateja** [comment]
yes that or you could just add line import config and access the variable as config.WORDS_API_KEY

@swapagarwal any reason for using os.environ.get() instead of normal referencing?

**Comment by swapagarwal** [comment]
`WORDS_API_KEY = os.environ.get('WORDS_API_KEY', config.WORDS_API_KEY)`
For local development, we can use config but when we check in the file to git version control, it exposes the API key which anyone can misuse, so we set it in environment.

**Comment by shanmukhateja** [comment]
:o never thought to that level.

**Comment by shanmukhateja** [comment]
but still any user needs to just open the config.py file and still see the codes right :/

**Comment by swapagarwal** [comment]
The config.py contains only the placeholders which have to be replaced for local development.

**Comment by shanmukhateja** [comment]
@swapagarwal I think you've forgotten to place WIT_ACCESS_TOKEN as placeholder as the key is visible. Pl check the config.py file and you'll understand.

**Comment by akarshHegde** [comment]
Hey, does this code work? i seem to get 500 response code for the get request in local dev.
```
token = os.environ.get('WORDS_API_KEY')
r = requests.get('https://wordsapiv1.p.mashape.com/words/' + word + '/definitions', headers = {'X-Mashape-Key':token})
```

**Comment by swapagarwal** [comment]
@shanmukhateja Nice catch, but that is a client side token, for verification purposes. The main token is still on the server itself.
@akarshHegde Yepp, that looks perfect!

**Comment by shanmukhateja** [comment]
@swapagarwal maybe some server side tweaks needs to be incorporated?

@akarshHegde did you check if the word variable is correctly detected? If I were you, I'd check that first!

**Comment by akarshHegde** [comment]
But how do i get it working on local dev? If the token resides on the server , will the code work on local dev setup?

**Comment by shanmukhateja** [comment]
Come over to gitter I think we are spamming here :/

**Comment by swapagarwal** [comment]
![](http://www.troll.me/images/pissed-off-obama/dont-worry-and-pullrequest-thumb.jpg)
