### ISSUE TITLE
Personalize the greeting message

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#23]
In the help module, replace `hi there` with the first name of the user.

**Comment by jorgeavaldez** [comment]
I can cover this one, I'll update with progress

**Comment by jorgeavaldez** [comment]
#37 pull request for this issue

**Comment by UshalNaidoo** [comment]
#110 Added a slightly more elaborate PR for this issue. Only noticed after that @jorgeavaldez had done something on this. You can use his, or a combination of both, I don not mind.

**Comment by SolidOrange** [comment]
Is this issue still open?

**Comment by Kashyap12** [comment]
hi is this still open ? @swapagarwal , new to open source, would love to contribute

**Comment by UshalNaidoo** [comment]
The PR has been created #110, waiting for @swapagarwal to merge it in

**Comment by swapagarwal** [comment]
@jorgeavaldez @UshalNaidoo @SolidOrange @Kashyap12 Thanks for your interest! You may work on other additions if you are still interested. 😄
