### ISSUE TITLE
movie module is down

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#242]
The backend API has gone private, and is no longer free.
https://www.patreon.com/posts/api-is-going-10743518
Look for an alternative.
P.S. It'd be great to have #207 resolved asap, rather than have people report that a module is down in the gitter chatroom! 😅

**Comment by edadesd** [comment]
What do you think of: https://www.themoviedb.org/documentation/api ?

**Comment by edadesd** [comment]
One disadvantage of using TMDb is that it doesn't generate an IMDB link the way OMDb did. I have a basic module patch for TMDb at: https://github.com/edadesd/JARVIS-on-Messenger/commits/movieAPI

**Comment by a1shadows** [comment]
Why not use the official rotten tomatoes api? It's legal and just as legit as imdb.

**Comment by edadesd** [comment]
Rotten Tomatoes and Fandango APIS: https://developer.fandango.com/

It sounds like the Rotten Tomatoes API only gives reviews and scores. The (related) Fandango API says it can give movie information, but from the documentation it doesn't appear that you can search by movie name. You have to search by location to get movies showing at nearby theaters.

**Comment by a1shadows** [comment]
TMDb it is, then.

**Comment by edadesd** [comment]
You can keep looking for another API if you want. I only linked to my TMDb patch instead of setting up a PR in case someone found a better API to use.

**Comment by swapagarwal** [comment]
IMDb id is important, as we only provide a gist of the movie information in the response.
Here's a relevant link: https://www.themoviedb.org/talk/5851f2ddc3a368258c0127b0 😉

**Comment by edadesd** [comment]
That's a good link, thanks for finding it. I'll work on a version that uses the TMDB ID to fetch the IMDB ID and makes an IMDB link.

**Comment by edadesd** [comment]
Opened PR #251 to address this.
