### ISSUE TITLE
telling the time and date in any part of the world feature can be added

### ISSUE THREAD

**Issue by abhihacker02** [swapagarwal/JARVIS-on-Messenger#243]
It's not telling date when asked.It's an easy feature to add

**Comment by edadesd** [comment]
We can possibly build a module that uses this API: https://timezonedb.com/api

**Comment by edadesd** [comment]
When I run it locally, JARVIS's response includes the day, date, and time. Could you show a screenshot of what your response looks like?

![jarvisdate](https://user-images.githubusercontent.com/18205943/28386975-2eab14ee-6c82-11e7-946a-755ebb27a2f5.png)

**Comment by swapagarwal** [comment]
@abhihacker02 As can be seen in the screenshot above, querying for `time at paris` will give you what you're asking for. Feel free to re-open if you'd like to extend it. 😄
