### ISSUE TITLE
Music module tests failing

### ISSUE THREAD

**Issue by edadesd** [swapagarwal/JARVIS-on-Messenger#245]
New pull requests are failing the Travis CI check based on failing the following test in test_music.py:

>assert ('music' == modules.process_query('play hotel california')[0])
>E       assert 'music' == None`

I wonder if something has changed in how the request processing API interprets that query.

**Comment by swapagarwal** [comment]
Nothing changed from our side; Retrained it to work as expected! (Not sure of the root cause.)
