### ISSUE TITLE
Introduction Message Error

### ISSUE THREAD

**Issue by KartikKannapur** [swapagarwal/JARVIS-on-Messenger#25]
When I enter a query such as `Who are you?` , like so `http://localhost:5000/process/?q=Who are you?` the output I get is `[null, {}]`.

It would probably be better if the output would be the content of the `help` variable under `modules/src/help.py`

**Comment by KartikKannapur** [comment]
@swapagarwal I have made a temporary fix for this issue. Let me know if this gets fixed after merging some of the other pull requests. Otherwise I'll send one in.

**Comment by swapagarwal** [comment]
I ran this and got `["help", {}]`.
Can you check again?

**Comment by KartikKannapur** [comment]
I checked it again and I got `["help", {}]` itself.
Surprising! I'm not quite sure why it returned `[null, {}]` the first time.
The issue is resolved, I'm closing it.
