### ISSUE TITLE
Add a Maths Module

### ISSUE THREAD

**Issue by avirlrma** [swapagarwal/JARVIS-on-Messenger#257]
Jarvis doesn't have a maths module till now so it can't answer even basic questions.If you like it to be there @swapagarwal , **I would like to implement it**.

**Comment by aviral1701** [comment]
@anyone?

**Comment by Utsal20** [comment]
I could give it a try @aviral1701

**Comment by aviral1701** [comment]
@Utsal20 I said i would be implementing it and have already started working on it. Just want to seek @swapagarwal approval

**Comment by edadesd** [comment]
I don't think you need to ask before writing up a module. Opening a pull request is how you get approval.
