### ISSUE TITLE
Movie: Add trailer link

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#259]
Refer the TMDb API documentation.

**Comment by agiridharan** [comment]
Can I help out here? @swapagarwal

**Comment by swapagarwal** [comment]
@agiridharan Sure, go ahead! 😄

**Comment by jwetzell** [comment]
I believe I have done this if no progress has been made.

**Comment by aviral1701** [comment]
@swapagarwal Can I make a PR to close this one quickly?

**Comment by darthgera123** [comment]
is this issue still open?
