### ISSUE TITLE
Replace links with buttons

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#26]
- [x] book
- [x] movie
- [x] request
- [x] wiki

**Comment by FleetAdmiral** [comment]
Hey could i take up this issue?

**Comment by swapagarwal** [comment]
@FleetAdmiral Sure, go ahead!

**Comment by UshalNaidoo** [comment]
#111 PR for button link on a book

**Comment by nubianMONK** [comment]
@swapagarwal seems like all Low-Hanging-Fruit issues that are fantastic for a newbie as my self, have all been scooped up.  Are you planning on creating a newer list of the aforementioned?

**Comment by SabareeshIyer** [comment]
Hey, is this open?

**Comment by swapagarwal** [comment]
@nubianMONK Thanks for taking an interest! Yes, I'll be adding a few more low-hanging fruits. You might want to keep an eye out for them.
@SabareeshIyer Sorry, this is closed now. You can work on other issues / new additions.
