### ISSUE TITLE
Movie: Correct Rating

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#260]
`happyness movie` returns Rating = 7.7
This rating is from TMDb: https://www.themoviedb.org/movie/1402-the-pursuit-of-happyness
IMDb rating is 8.0 (http://www.imdb.com/title/tt0454921/)

Options:
* Rename field "Average Rating" to "TMDb Rating"
* Retrieve and show IMDb rating

**Comment by ahmedsadman** [comment]
I can work on this. There is no IMDB API available, so I want to do this: get the IMDB id from TMDB API, then use the IMDB id to construct a full IMDB website link, and scrape the Rating. Is that okay?
**And yes, can I work on this module while the WIT AI response problem still persists?** I think the AI is taught in the older version style, right?

**Comment by swapagarwal** [comment]
Let's explore more options (avoid scraping). The Wit response structure update doesn't affect jarvis, for old as well as new modules. The effect is seen when you create a **new app** for testing purposes.

**Comment by ahmedsadman** [comment]
Well, do you have any other option in mind? Please let me know.
And if wit response doesn't affect new modules, how do you propose to use WIT if I want to continue working on the Soccer module? I need to create new app so that I can train it about user inputs, right? And Soccer module is new of course. Frankly speaking, I am highly confused at this stage: At one time, you're saying that new modules are not affected, again, you're saying that effect is seen only when creating new apps. **So, how contributors can create new modules without creating new apps?**

**Comment by swapagarwal** [comment]
New modules (soccer) in old app (jarvis) are not affected.
If you create new app (say jarvis-test), it will have new response structure.
While submitting a Pull Request, you only submit the module code. I'll train the new module (soccer) in old app (jarvis), so it'll have the old response structure. Hope that makes sense! 😅

**Comment by ahmedsadman** [comment]
Oh! That's what I was asking for days. When I asked for help, some people in Gitter told me that I need to create own app in WIT to make module. I never knew that you were going to train that for me. 
It was the only barrier between me and soccer module, I will start on that right away!

**Comment by swapagarwal** [comment]
So you can create your own app for testing purposes, till your module is integrated. Sorry for the misunderstanding! 😞

**Comment by ahmedsadman** [comment]
Okay, about the IMDB rating: you already know that OMDB provides api that can fetch IMDB rating, what if we use OMDB just for fetching the Rating?

**Comment by swapagarwal** [comment]
OMDb API is not free anymore, hence we moved to TMDb.

**Comment by ahmedsadman** [comment]
What about this: http://imdbpy.sourceforge.net/

**Comment by edadesd** [comment]
IMDbPY looks promising. If you were to use that to get an IMDB rating, I think it would make sense to just rely on it for all of the information that the module fetches.

**Comment by ahmedsadman** [comment]
Then I am starting to work on it.

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ahmedsadman** [comment]
Done. See #268
