### ISSUE TITLE
Adding modules with APIs

### ISSUE THREAD

**Issue by sync350** [swapagarwal/JARVIS-on-Messenger#263]
This is more of a question than an issue. I am looking at adding a couple of modules to JARVIS, for starters I'd like to add a stock ticker. I have the code pretty much laid out, but it relies on an API key, as most of the modules do. I see that most of the modules reference an external config file so as to not make the API key public. Is there a certain way you want the API key referenced?

**Comment by edadesd** [comment]
Here's an example of how @swapagarwal referenced a new API key: https://github.com/swapagarwal/JARVIS-on-Messenger/commit/52e0f2561e970097acb56e475e4539563069e099#diff-7717e6031799299412c6e4fec2df670fR10

**Comment by swapagarwal** [comment]
Adding to @edadesd, this structure has two advantages:
1. You can test locally by setting your API key in config.py
1. In production environment, the key is not hard-coded. It is picked up from an environment variable.
