### ISSUE TITLE
JARVIS does not return expected value for movies

### ISSUE THREAD

**Issue by agiridharan** [swapagarwal/JARVIS-on-Messenger#267]
![jarvis error](https://user-images.githubusercontent.com/14183971/29201832-bda9512e-7e16-11e7-9acf-b797ffeb13bf.png)

Jarvis is supposed to return the title of the movie, the release date, the rating and an overview

**Comment by ahmedsadman** [comment]
It returns expected movies without any problem, I just tested it using your inputs.

**Comment by edadesd** [comment]
I got the correct returns from my local fork as well. I agree with @ahmedsadman that it seems like an issue with the API key.

**Comment by swapagarwal** [comment]
Looking into it.

**Comment by swapagarwal** [comment]
Fixed. There was a syncing issue between code on github and that on server. 😅
