### ISSUE TITLE
Move spotify token to a folder

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#275]
This folder can contain more tokens like this, if required.

**Comment by azie-ginanjar** [comment]
@swapagarwal can I take on this one?

**Comment by azie-ginanjar** [comment]
@swapagarwal I've tried query = "songs by linkin park" but always got confidence below 0.5, so I always got response {"text": "I'm sorry; I'm not sure I understand what you're trying to say.\nTry typing \"help\" or \"request\""}

**Comment by swapagarwal** [comment]
I've opened an issue for easier testing. That should solve this problem! 😄
