### ISSUE TITLE
Sample query 'roll a die' doesn't working on the local testing

### ISSUE THREAD

**Issue by isbee** [swapagarwal/JARVIS-on-Messenger#286]
I do not know if there is a typo in the document or if the implementation is not working properly, but the query does not work with 'roll a die' but with 'roll a dice'.

![image](https://user-images.githubusercontent.com/24961200/30794571-eda6622a-a203-11e7-8014-fe6be045789b.png)

My working environment is  ubuntu 16.04 LTS and I am testing only sample queries without any code modification.

![image](https://user-images.githubusercontent.com/24961200/30794676-93f0d386-a204-11e7-9cb5-0f803db0926a.png)

![image](https://user-images.githubusercontent.com/24961200/30794692-a6cfddbc-a204-11e7-99c6-cecdc7f6c707.png)

![image](https://user-images.githubusercontent.com/24961200/30794702-b3e8ca18-a204-11e7-905d-3749f37250ed.png)

**Comment by djung460** [comment]
Are you going to make a PR to update the README?

**Comment by isbee** [comment]
@djung460  sure! I'm not familiar with it because I'm new on open source project. I'll pull request soon.

**Comment by djung460** [comment]
Typically you keep an issue opened until the solution/feature PR has actually been approved and merged. @isbee

**Comment by isbee** [comment]
@djung460  I was a fool. learned a lot from you

**Comment by djung460** [comment]
lol don't be hard on yourself

**Comment by swapagarwal** [comment]
Hey @isbee, thanks for reporting this issue. It has now been fixed! 😄
