### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#290]
- [x] Publish an Introductory Post
- [x] Create a new label
- [x] Assign #hacktoberfest label to issues

**Comment by swapagarwal** [comment]
https://medium.com/jarvis-on-messenger/hacktoberfest-cff4d01f4a6

**Comment by darshkpatel** [comment]
any issues for hacktoberfest ?
cannot find any tags :/

**Comment by swapagarwal** [comment]
https://github.com/swapagarwal/JARVIS-on-Messenger/labels/Hacktoberfest
