### ISSUE TITLE
Add a issue and PR template.

### ISSUE THREAD

**Issue by aviral1701** [swapagarwal/JARVIS-on-Messenger#293]
I think we should have a Issue and Pull Request template as sometimes there is a lot of ambiguity in what the creator wants to say,if he wants to work on it,if its bug or a feature request etc.

**Comment by swapagarwal** [comment]
Hey @aviral1701, I totally agree that this would standardize things here. Would you like to take it up? 😄

**Comment by aviral1701** [comment]
Sure! Just give me a couple of days. 
Happy Diwali mate!

**Comment by swapagarwal** [comment]
Great! A very happy diwali to you too! 😄
