### ISSUE TITLE
video link in persistent menu not working

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#297]
In the persistent menu, go to "Common Queries", "Media", and click on "videos of sia".
It returns an error.
Investigate why this is not working.

**Comment by oddurad** [comment]
I'd like to take a look at this

**Comment by oddurad** [comment]
I've also opened an issue on the YouTube API Issue Tracker here: https://issuetracker.google.com/issues/67448436

**Comment by swapagarwal** [comment]
@oddurad Really appreciate you going the extra mile here by opening a detailed issue above! 💯
