### ISSUE TITLE
Roll a die doesn't work

### ISSUE THREAD

**Issue by Astrophilic** [swapagarwal/JARVIS-on-Messenger#303]
![issue](https://user-images.githubusercontent.com/25284819/31585856-724902a2-b1e6-11e7-97e4-3674b5a49828.JPG)
@swapagarwal  I have just started working with open source . I opened the link and found this bug as there is no output for the required query!!! How do i fix this??

**Comment by swapagarwal** [comment]
Hey @Astrophilic, nice catch and welcome to the world of open-source! 😄 
The intent handling is done by Wit. See wit.ai for more information.
For fixing this, you can add the query in https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/local/wit.json
Feel free to ask any questions you may encounter along the way! 😄

**Comment by Astrophilic** [comment]
@swapagarwal ,If you can help me by giving an example of a query and regarding the local testing, i tried installing all the required modules using pip and then when i tried running the file 
![error](https://user-images.githubusercontent.com/25284819/31669538-0116236a-b373-11e7-8f10-9bce76ffd9b3.JPG)
I get this error.
I tried fixing this by
adding this to 
**import sys
sys.path.append('../src')**
to __init.py but the problem continues.
How do i fix this??

**Comment by swapagarwal** [comment]
I think you're running on Python 3. Jarvis runs on Python 2! :smile:

**Comment by Astrophilic** [comment]
which version exactly?? I installed python 2.7 and it gave some error again!!

**Comment by swapagarwal** [comment]
In your terminal, type `python` and press `Enter`. Paste the screenshot here.

**Comment by Astrophilic** [comment]
![sw](https://user-images.githubusercontent.com/25284819/31682531-fa967722-b397-11e7-91fd-4cf0348f653b.JPG)
Actually i had initially python3.6 installed .
Then i installed python2.7 and added it to the path but with a different name then 
since pip doesn't come pre installed with 2.7 .
I installed it after following a google search.
since my scripts folder for python 3.6 are in the path so i could not use pip directly as it was referring to the pip of 3.6 so i manually inserted the address 
and ran the following command
![aas](https://user-images.githubusercontent.com/25284819/31682717-92986e54-b398-11e7-93ba-40dce20ec780.JPG)
but after running this command at some point during the execution
![errrr](https://user-images.githubusercontent.com/25284819/31682948-21065a0c-b399-11e7-997d-cfc3225d3f5a.JPG)
I have gcc installed manually and i can compile so c compiler is installed..!!
but i can not figure out how exactly to fix this

**Comment by swapagarwal** [comment]
Can you try removing `IMDbPY` in `requirements.txt` and run `pip install...`?

**Comment by Astrophilic** [comment]
yeah It worked :relieved: I removed the module and then i had to modify __init__.py and again remove movies.py and then it works like this!
![ache](https://user-images.githubusercontent.com/25284819/31685389-6961beca-b3a0-11e7-9fac-405bc7cf2710.JPG)

**Comment by Astrophilic** [comment]
Thanks a bunch  :simple_smile:  You talked of wit.ai I watched a video on youtube and then i could understand what exactly it is!!! Now that I shall try to make that roll a die thing work!!!
how should i proceed???

**Comment by swapagarwal** [comment]
Awesome @Astrophilic! Would you like to create a PR adding that video to README?
You can override the query result here: https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/local/wit.json

**Comment by Astrophilic** [comment]
I added the video link to the file CONTRIBUTING.md. I had another video which is a demo of the ai as in how it works!!!
I tried embedding it to the readme but I could not generate the thumbnail for 
 this is the [video](https://vimeo.com/238717639) which i think would be apt to put in the readme.
But I am not able to generate a thumbnail like [this](https://i.vimeocdn.com/video/645512677_640.jpg).
How do i do that???

**Comment by Astrophilic** [comment]
well, I have added some more changes!!! and I could embed the image!! finally!!

**Comment by enriqueav** [comment]
Roll a dice works if you clone and run the project:

![captura de pantalla 2017-10-18 a las 22 45 21](https://user-images.githubusercontent.com/13837490/31753441-2cf1aad4-b456-11e7-8b01-f2bba59eefa5.png)

Perhaps the query is only missing in the .json that the production instance is reading.

**Comment by Astrophilic** [comment]
@enriqueav can you please elaborate how do i add a query and which json file should be modified ?? so that I could generate the same output!!!

**Comment by enriqueav** [comment]
@Astrophilic  It works if you clone the project and follow the steps to run and test your local instance.
It is just not working for the hosted version, the one you talk to in messenger.

Anyway, FYI, the query goes here:
https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/local/wit.json
You need something similar to the "songs by linkin park" query, if you need entities (arguments), or similar to "test", if you don't need entities.

**Comment by Astrophilic** [comment]
![uplo](https://user-images.githubusercontent.com/25284819/31852806-13ed39fc-b69c-11e7-8172-9c1a2b0f8bc0.JPG)
It runs on my local machine but it doesn't give the output which in your case gives!!!

**Comment by enriqueav** [comment]
You may have a typo. Try "dice" instead of "die"

**Comment by Astrophilic** [comment]
Thanks @enriqueav  It works!! now!!! 😆 .

**Comment by edadesd** [comment]
If the Wit.AI only treats "dice" as the correct intent and not "die" then we probably need to update the suggestion shown in the screenshot at the top of the thread.

**Comment by swapagarwal** [comment]
Hey @enriqueav. To clarify, the production instance does not have a long list of json entries. It is driven by natural-language processing. We train the AI using some sample inputs for a module, and then it tries to classify a new input from the user into one of the modules. 😄 
@edadesd It works now. 😇
