### ISSUE TITLE
Roll a die not working

### ISSUE THREAD

**Issue by bigyankarki** [swapagarwal/JARVIS-on-Messenger#330]
Jarvis does not reply when messaging "roll a die".

**Comment by kz3838** [comment]
I looked through the code, does it need to specify what kind of die? Or did I miss something? (This is my first time with this kind of thing so sorry if it's wrong)

**Comment by swapagarwal** [comment]
Hey @bigyankarki, thanks for reporting this issue. It has now been fixed! 😄
