### ISSUE TITLE
Twitter integration

### ISSUE THREAD

**Issue by H3ADLESS** [swapagarwal/JARVIS-on-Messenger#336]
Hey guys,

we  (a friend of mine and me) would like to integrate the possibility to ask Jarvis for recent tweets on Twitter, using the [Twitter API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets). Simply ask Jarvis something like: "What's up on twitter?" and get some popular tweets back. 

What do you guys think about this idea? Is there anything against for us to do this?

Best regards!

**Comment by utkarshdeep** [comment]
I think its a good idea. But I think some different variant of the question: "What's up on twitter?", should also trigger Twitter API. Like "What's trending today?" etc.

**Comment by H3ADLESS** [comment]
Sure. The question was just an example. So we will start working on this. Thanks for your reply.

**Comment by utkarshdeep** [comment]
@H3ADLESS If you need any help, I'll be available.
