### ISSUE TITLE
Move from hello to bye

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#339]
https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/hello.py#L10

^ This does not seem an appropriate response for `hello`. Let's move it to `bye`.

**Comment by dkansk1323** [comment]
I can do that.

**Comment by orbit-stabilizer** [comment]
I ended up doing this, as it seems like dkansk1323 has not completed it yet - I hope that's okay. 

945bf558eb6feab58bb981988dcc1c578125f5df
e0744454e61eb4dcc1172bf64c2f5083dc60f29f

**Comment by dkansk1323** [comment]
It's already done sorry for late comment
[https://github.com/swapagarwal/JARVIS-on-Messenger/pull/342/commits/f65a041b9579957a1435e3914d9933d3bcd3a2e6](url)

**Comment by dkansk1323** [comment]
It's already done... sorry for late comment.
#342

**Comment by cysys** [comment]
Is this bug fixed or is it still available to be worked on ? I am a beginner hoping to contribute.
