### ISSUE TITLE
Caching results to limit requests to APIs

### ISSUE THREAD

**Issue by havanagrawal** [swapagarwal/JARVIS-on-Messenger#34]
A lot of API guidelines have one thing in common; they either limit the number of requests made per day, or throttle requests, especially in case of free APIs.

In such a case, eventually, users will be unable to avail these services even if they are repeating a query.

For API's where real-time results are not required (eg: movies, books, jokes, wiki) and **where caching is not against the policy of using the API**, we could maintain a server-side cache of the results.

For queries with randomized results (like jokes, quotes), we could enter a small probability that the joke is picked up from the cache, rather than a new request (of course, this is just an example.. If we use our own joke/quote list, this won't be required, but the principle applies to most other API's we'll use eventually)

**Use cases:**
1. I'm trying to decide which book to buy. I ask JARVIS for the rating of _Throne of Glass_. Then I ask it for _Lady Midnight_. But being my absent minded self, I forget the rating _Throne of Glass_ had, and so I query it again. But alas, the query limit has been exceeded, and I can't see the rating anymore :disappointed: Must wait till tomorrow to decide.
2. I have an upcoming math test :scream: I ask JARVIS to tell me about the _Pythagoras theorem_, but eventually, because of exam stress :books: I forget it. So I ask it again, but alas, Wikipedia has crashed because it's exam time everywhere, and now I'm going to fail :sob:

**Comment by swapagarwal** [comment]
Hey @havanagrawal, this will actually be quite useful (or more appropriately, required as we expand).
I'll take a look on how to do this, keeping in mind that not all responses can be cached (as you correctly pointed out). Meanwhile, if you get any ideas (approaches), do share on this page.
P.S. Do you use an extension for using those emojis or do you know 'em all? :stuck_out_tongue_winking_eye:

**Comment by havanagrawal** [comment]
The way I see it, there are two scenarios
1. Keyword-less queries: Jokes, quotes, etc do not need entities, only intents, so we could maintain a simple dictionary-like cache, with key as (say) "joke", and the value being a queue of the least-recently-shown jokes
2. Keyword queries: Books, movies, etc have an entity associated with them, and so we'd somehow need to maintain a dictionary-like structure of "book" to entity to actual result. This could quickly get too complex if not designed well.

Not sure how practical this approach would be. Let's see if someone else has any ideas.

**Comment by MrRobot9** [comment]
I tried using `requests-cache` , it works perfectly fine!! Can I create a pull request ?
