### ISSUE TITLE
Stock prices.

### ISSUE THREAD

**Issue by maulikjs** [swapagarwal/JARVIS-on-Messenger#350]
I want to work on getting stock prices from AlphaVantage API.
Is anyone else working on it?

**Comment by nmshaikh** [comment]
I had the same idea as you but if you've already started working on it, I'll try to think of something else :) Would love to see what you implement and add to it if I can

**Comment by nmshaikh** [comment]
@maulikjs Yes I'd love that! This is actually my first ever time contributing to open-source so I could use some guidance. 

I actually had an idea to add a module for random recipes. So you can ask JARVIS for something like 'a chicken recipe' or 'a good recipe for breakfast' and you get appropriate responses. If I understand correctly, I should start a new issue and state my idea there, right?

**Comment by maulikjs** [comment]
@nmshaikh haha stocks was my 2nd too. this is a great project to start with. Do you have any thoughts on how youll go about doing this?

**Comment by nmshaikh** [comment]
@maulikjs I'm guessing it can implemented like the [news](https://github.com/swapagarwal/JARVIS-on-Messenger/commit/59beb1ca0a0f5210ebf44809282d0cc7d3d42874) module. @swapagarwal has provided a wonderful list of APIs we could use at this [link](https://github.com/toddmotto/public-apis). 

So on the wit side, the processor would need to detect whether the user just asked for a random recipe, or whether they included criteria such as 'chicken', 'beef' etc. or maybe 'dinner', 'breakfast' etc.

Should I start an issue for this?
