### ISSUE TITLE
Movie module not working due to change in IMDbPY

### ISSUE THREAD

**Issue by JindalMohit** [swapagarwal/JARVIS-on-Messenger#375]
## What are the steps to reproduce this issue?
1. Type `<something> movie` and it will always show an error.

## Cause :
The IMDbPY library has broken due to some changes in the imdb website. See here
[https://stackoverflow.com/a/47955420/7689743](https://stackoverflow.com/a/47955420/7689743)

There is no `rating` key anymore and that cause and error on [this](https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/movie.py#L46) line.

## Possible Fix :
Use `imdbparser` instead of `IMDbPY`. See here : 
[https://pypi.python.org/pypi/imdbparser/1.0.3](https://pypi.python.org/pypi/imdbparser/1.0.3)

**Comment by swapagarwal** [comment]
Thanks @JindalMohit for reporting the issue.
Also, kudos for investigating the root cause and proposing an alternative! 💯
