### ISSUE TITLE
Add a curated list of jokes

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#4]
The API call in the `joke` module can be prevented by adding a curated list of jokes in the source file itself.
Pros:
- Fewer API calls
- Curated jokes (only include the ones that tickle your funny bone)
- No offensive jokes (sometimes the API returns such type of jokes)

Con:
- The curation effort (only one time!)

**Comment by havanagrawal** [comment]
Hi, I'd like to contribute to this repo.. Please let me know if I can contribute :)
As a small suggestion, perhaps the joke module could have genres, such as "knock knock", "walk into a bar", "meta", "puns", etc. 
The user would interact by saying "tell me a knock knock joke". If no genre is mentioned, we just pick out a random one.

**Comment by swapagarwal** [comment]
You are welcome to contribute!
Only with the help from the community can this become something big.
I like the idea of having genres; I didn't implement it as I couldn't find relevant APIs.
Would you be interested to take this issue and make a list of category-wise good jokes?

**Comment by shanmukhateja** [comment]
Hi what should be the **deciding factor** if a joke should be delivered by the API call or from the pre-compiled list within JARVIS?

**Comment by swapagarwal** [comment]
If we can hand-pick a minimum number (say 10-15) of funny jokes, then we'd remove the API call.

**Comment by shanmukhateja** [comment]
But don't you think it would be just repeatedly showing these 10-15 only? I think we should make use of both of them.

**Comment by shanmukhateja** [comment]
Also I propose we use a jokes.txt file for this list.

**Comment by swapagarwal** [comment]
Those 10-15 can be expanded with time,
The problem with using an API is that sometimes, their jokes can be offensive to someone, so that's why we want hand-picked jokes!

**Comment by shanmukhateja** [comment]
Understood. I'll submit some 10-15 for starters. We can expand later :)

**Comment by shanmukhateja** [comment]
![ss_joke](https://cloud.githubusercontent.com/assets/5269580/15098490/c67838f2-155c-11e6-9304-11816ee95662.png)
So this is how it's coming up!
 If it's OK...I'll send a pull request. @swapagarwal

**Comment by shanmukhateja** [comment]
I put a \t\t\t between the joke as a syntax for handling Q&A model jokes.

**Comment by swapagarwal** [comment]
@shanmukhateja You can send a PR and then we can take the discussion over there. :smile:

**Comment by shanmukhateja** [comment]
Now that this is resolved, shouldn't we close this issue @swapagarwal ?

**Comment by swapagarwal** [comment]
I'd like to keep this open for newbies to get started with (by adding some more jokes). :smile:

**Comment by shanmukhateja** [comment]
well then they can open a new one right? Like referencing the same issue multiple times for different commits by different ppl isn't much convincing
 don't you think?

**Comment by shanmukhateja** [comment]
They can just open a new issue later ;)

**Comment by swapagarwal** [comment]
Yepp, they can open a new one but keeping this open would encourage new people to start contributing!

**Comment by swapagarwal** [comment]
Continued in #54
