### ISSUE TITLE
Anime rating

### ISSUE THREAD

**Issue by akarshHegde** [swapagarwal/JARVIS-on-Messenger#40]
Hey, I was thinking of working on the Anime rating feature. There is this Api from [hummingbird.me](https://hummingbird.me/) that seems to be reliable and easy to use.

Check the api structure:

[API-v1](https://github.com/hummingbird-me/hummingbird/wiki/API-v1-Methods )

Let me know your thoughts

**Comment by shanmukhateja** [comment]
I'm getting a 404 error in every query. :/

**Comment by swapagarwal** [comment]
@akarshHegde Nice find; looks great! Go ahead, I'll be waiting for your PR. Hit me up if you need any help. :smile: 
@shanmukhateja `https://hummingbird.me/api/v1/search/anime?query=death+note`

**Comment by akarshHegde** [comment]
It seem to work for me. Could you suggest some titles which didn't work for you?
![anime](https://cloud.githubusercontent.com/assets/8245969/15272201/d3071b4a-1a8b-11e6-97dd-65511849fe5f.png)

**Comment by shanmukhateja** [comment]
It's working. I was sending the query wrong :p (guilty guilty)

**Comment by akarshHegde** [comment]
Hey @swapagarwal  the PR is ready, but i am not sure how to write the test cases.(I didn't quite understand how tests work :astonished: ) Any suggestions?

**Comment by swapagarwal** [comment]
You sure learn fast!

**Comment by akarshHegde** [comment]
:grin:
