### ISSUE TITLE
define superhero throws error; other define statements work fine

### ISSUE THREAD

**Issue by shanmukhateja** [swapagarwal/JARVIS-on-Messenger#43]
So I was testing Jarvis for any bugs and have stumbled upon this.

The thing is if you type "define <anything>" it works but if "define superhero" is issued, it shows the "Something didn't go well" or some message like that. (It's clearly a bug).

**Comment by swapagarwal** [comment]
The Words API doesn't include the definition of superhero. Nothing we can do about that.

**Comment by shanmukhateja** [comment]
Maybe a better error message to deal with such situations would be nice don't you think?

**Comment by swapagarwal** [comment]
#19
