### ISSUE TITLE
Random fact feature

### ISSUE THREAD

**Issue by akarshHegde** [swapagarwal/JARVIS-on-Messenger#44]
Hey, There is this interesting api i found, which provides random facts related to numbers and dates. We could use this for now.
[Numbersapi](http://numbersapi.com)

Another one, 
[FactAPI](http://www.fayd.org/api/)
(returns data in xml)
Let me know your opinions :smiley:

**Comment by shanmukhateja** [comment]
it's pretty good. I think we can add a facts module and for starters include this it.
Later, we can improve the facts module to include other types of facts too.

**Comment by akarshHegde** [comment]
Yep, exactly! 
@swapagarwal whats your say?

**Comment by swapagarwal** [comment]
Looks good, go ahead with `http://numbersapi.com/random/trivia`
