### ISSUE TITLE
Random fact module needs work

### ISSUE THREAD

**Issue by shanmukhateja** [swapagarwal/JARVIS-on-Messenger#49]
The random fact module needs some work. I have noticed two issues:

1) The are exponential values not being superscripted and so we have values like **6.022e+23** in the output.
2) There are few characters like the single quotation mark which is sometimes shown as \U2019.

This is a medium priority bug and I feel it can be assigned the _Low hanging fruit_ label too.

**Comment by akarshHegde** [comment]
random fact module or random joke module? :confused:

**Comment by shanmukhateja** [comment]
Fixed. thank you :)

**Comment by swapagarwal** [comment]
#15
