### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#51]
Below is the list of modules that need a `output['error_msg']` in case of an exception:

- [x] anime
- [x] book
- [x] currency
- [x] dictionary [Line#20](https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/dictionary.py#L20)
- [x] movie
- [x] music
- [x] time
- [x] wiki

**Comment by jorgeavaldez** [comment]
I can take this

**Comment by swapagarwal** [comment]
sure @jorgeavaldez, let me know if you need any help! :smile:

**Comment by camdroid** [comment]
@jorgeavaldez Are you still working on this, or would it be okay if I worked on a couple modules?

**Comment by camdroid** [comment]
Added pull request for currency (#65) and anime (#66).

**Comment by nikhilgeo** [comment]
@swapagarwal ...I like to work on this..!!

**Comment by swapagarwal** [comment]
@nikhilgeo This is being done in #74 
Feel free to take up any of the other [issues](https://github.com/swapagarwal/JARVIS-on-Messenger/issues?q=is%3Aissue+is%3Aopen+label%3A%22Low-Hanging+Fruit%22). :smile:

**Comment by nikhilgeo** [comment]
ok...Cool..!!
