### ISSUE TITLE
Time zone module

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#52]
Support queries like "time in US"

**Comment by brandon-pineda** [comment]
Hello, I'd like to contribute on this.

**Comment by swapagarwal** [comment]
Hey @brandon-pineda, thanks for your interest but this is done in #64. I suggest you start out with other low-hanging fruits here https://github.com/swapagarwal/JARVIS-on-Messenger/labels/Low-Hanging%20Fruit
