### ISSUE TITLE
Add offline data sources

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#54]
Below is the list of modules that can make use of an offline data source:

- fact
- joke
- quote

Add (Improve) the curated lists in `data/*` folder. Comment below if you'd like to take up one of these.

**Comment by jorgeavaldez** [comment]
I can take this

**Comment by swapagarwal** [comment]
sure @jorgeavaldez, let me know if you need any help! :smile:

**Comment by nikhilgeo** [comment]
I like to take it up...

**Comment by swapagarwal** [comment]
@nikhilgeo Sure, go ahead!

**Comment by williamshoops96** [comment]
I've added some facts, about to pr now!
