### ISSUE TITLE
Rule based to NLP. Are you sure?

### ISSUE THREAD

**Issue by kunal15595** [swapagarwal/JARVIS-on-Messenger#6]
You shifted from a rule based system to an *online* NLP based system. Is it a complete shift? This would mean that the system would not work offline. This would adversely affect in case of slow internet connection.

**Comment by swapagarwal** [comment]
Yes, it's a complete shift for now.
However, both the models reside independently in different branches (master and legacy) for any use.
For the system to work offline, the messenger server would have to be local which is not the case.
So, anyway, whenever you're messaging the bot, the processing is done server-side (whether it's rule based or NLP) so the client should not be affected by this.

**Comment by kunal15595** [comment]
cool
