### ISSUE TITLE
Time queries not working properly for all locations

### ISSUE THREAD

**Issue by manparvesh** [swapagarwal/JARVIS-on-Messenger#67]
As you can see in the screenshot below, for some locations the query in the form *time in ___* works perfectly fine, but the query *____ time* doesn't. 
![screenshot from 2016-06-06 18-43-35](https://cloud.githubusercontent.com/assets/6629115/15823152/0bd980c4-2c17-11e6-9125-e3414fa130e1.png)

**Comment by swapagarwal** [comment]
@manparvesh, nice catch! :wink: 
Thanks for testing and taking the time to report this issue. :smile: 
I'll look into this.

**Comment by krizhan1997** [comment]
thats wierd. i'm currently in toronto. i just checked and the times was correct for new delhi when i did it in toronto??

**Comment by swapagarwal** [comment]
@manparvesh As this module was added yesterday only, there weren't enough queries to train on. This should be fixed now. Can you confirm?

**Comment by manparvesh** [comment]
I tried it just now. None of the query seems to work now.

**Comment by swapagarwal** [comment]
Ohh, my bad! Can you recheck?

**Comment by manparvesh** [comment]
Working fine now :smile:
