### ISSUE TITLE
Songs

### ISSUE THREAD

**Issue by manparvesh** [swapagarwal/JARVIS-on-Messenger#71]
If I enter a query for which the bot is unable to find a match, it doesn't reply anything (when I entered *chrs brown* instead of *chris brown*). I had to wait for some time to realize that :stuck_out_tongue_closed_eyes: 
Also, no responses for *wiz khalifa*? :scream: 
![screenshot from 2016-06-07 10-46-18](https://cloud.githubusercontent.com/assets/6629115/15846687/36e19dfc-2c9d-11e6-9775-40e47b315e95.png)

**Comment by williamshoops96** [comment]
I've added error messages in my pr #74
