### ISSUE TITLE
Time: Format output

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#80]
Current: `2016-06-09 13:24:43`
New: `Thu Jun 09 2016 13:24:43`
[Line#17](https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/src/time.py#L17)

**Comment by swapagarwal** [comment]
http://strftime.org/

**Comment by wickedsmirk** [comment]
Hey! have you considered adding a feature which will send a reminder after a specified time? Sort of like an alarm or a countdown timer.

**Comment by swapagarwal** [comment]
Hmm, sounds good. The only issue is that this would require a database to store the alarms.
If we get enough good features that require a database, we'd definitely support them! :smile:

**Comment by nikhilgeo** [comment]
PR #84 created for change in time format

**Comment by nikhilgeo** [comment]
New PR #85 create with time format check in
