### ISSUE TITLE
Show rating scale

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/JARVIS-on-Messenger#81]
Show the maximum rating, like `3.73 / 5` instead of just `3.73`.

- [x] anime
- [x] book
- [x] movie

**Comment by nikhilgeo** [comment]
I guess these are the places where changes need to be done.. ?
movie.py line no: 11
anime.py line no: 15
book.py line no: 25

I can take this up....

**Comment by swapagarwal** [comment]
@nikhilgeo Sure, go ahead! :smile:
