### ISSUE TITLE
Response for 'bye'

### ISSUE THREAD

**Issue by wickedsmirk** [swapagarwal/JARVIS-on-Messenger#87]
Currently Jarvis responds with-
"I'm sorry; I'm not sure I understand what you're trying to say sir.
Try typing "help" or "request" for a "bye"
It should have a better system to deal with keywords such "bye" ,"thanks you" etc

**Comment by swapagarwal** [comment]
Agreed, this module is planned.
You are welcome to contribute as well! :smile:

**Comment by rohshar** [comment]
I implemented a simple bye module and have created a pull request.

**Comment by swapagarwal** [comment]
#97
