### ISSUE TITLE
Music Lyrics API : Genius

### ISSUE THREAD

**Issue by VarunWachaspati** [swapagarwal/JARVIS-on-Messenger#95]
Hey

I think the Genius API would be great for serving lyrics. https://docs.genius.com/

Best thing about Genius is it's annotations which actually specify the meaning and context of particular lines in a song. Great value add-on for JARVIS

What are your thoughts on this?

**Comment by swapagarwal** [comment]
@VarunWachaspati Sorry, I missed this somehow! 👍 for the annotations; would you like to implement this?
Either Genius or MusixMatch works fine by me. 😄

**Comment by seongju** [comment]
I did a little research and it seems that without paying Musixmatch does not give a 'Full Lyrics Display' also Genius does not give the lyrics either.

**Comment by shaishavgandhi05** [comment]
There's http://api.chartlyrics.com/ that provides lyrics for non-commercial use. I don't know if Jarvis would qualify for non-commercial use. Scroll down to bottom to read their terms of use.

**Comment by robertodessi** [comment]
Hi, 
I would like to give my first contribution to this interesting project. 
Is anybody working on this?

**Comment by swapagarwal** [comment]
@shaishavgandhi05 Yes, we can use the ChartLyrics API.
@robertodessi Sure, go ahead!

**Comment by lakshaykalbhor** [comment]
Hey everyone, though @seongju is right that Genius's API does not directly provide lyrics, but it provides the url of a page that contains the lyrics. Lyrics can be obtained by simply scraping that page. I have sent a [Pull Request](https://github.com/swapagarwal/JARVIS-on-Messenger/pull/149) and have tried adding a lyrics search option which uses Genius's API.

**Comment by swapagarwal** [comment]
Closed in #149
