### ISSUE TITLE
ImportError: No module named 'src'

### ISSUE THREAD

**Issue by rohshar** [swapagarwal/JARVIS-on-Messenger#96]
I was trying to get jarvis running on my machine but i got an import error that it can't find src.

Did I do something wrong?

**Comment by swapagarwal** [comment]
Can you provide a screenshot of your terminal?

**Comment by rohshar** [comment]
nevermind, I got it to work. Where are the files in modules/src being called from?

**Comment by swapagarwal** [comment]
https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/modules/__init__.py#L29

**Comment by JotraN** [comment]
Hi, just wanted to say I ran into this issue as well. The problem was that I mistakenly ran jarvis using python 3.5.2 and not python 2.7. Just in case anyone else runs into this issue, use the correct python version.
