### ISSUE TITLE
Toss a coin feature

### ISSUE THREAD

**Issue by rkrp** [swapagarwal/JARVIS-on-Messenger#99]
Hey, I think it would be nice to have a simple feature where the users can ask JARVIS to toss a coin and it randomly replies either 'Head' or 'Tail'. What do you think of it?

**Comment by badmon** [comment]
while this seems like an amazing bot functionality, we should not rob people of the fun and anticipation in actually tossing a coin

**Comment by rkrp** [comment]
@badmon Not really sure how should I take your comment :sweat_smile:

**Comment by swapagarwal** [comment]
@rkrp What comment? :stuck_out_tongue_winking_eye:

**Comment by badmon** [comment]
Lol

**Comment by rkrp** [comment]
@swapagarwal Apparently, @badmon has removed the comment, he last made - to which I replied to. 

> while this seems like an amazing bot functionality, we should not rob people of the fun and anticipation in actually tossing a coin

And yes, I would love to work on this :smile:

**Comment by badmon** [comment]
all i'm trying say is this bloats the bots functionality

**Comment by swapagarwal** [comment]
@rkrp Ok, I'll be waiting for your PR! :smile: 
@badmon This is debatable. However, we can always disable some modules by changing just one line in init.py so there's no harm in making new modules!

**Comment by seongju** [comment]
Hello @swapagarwal, I've submitted a PR for this feature #106. Thanks

**Comment by swapagarwal** [comment]
Added in #106
